
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.Tbitem Tbitem {get; }
    public demo.Tbreward Tbreward {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        Tbreward = new demo.Tbreward(loader("demo_tbreward"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbitem.ResolveRef(this);
        Tbreward.ResolveRef(this);
    }
}

}
