
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


 
export enum AccessFLag {
    /**
     * 读
     */
    READ = 1,
    /**
     * 写
     */
    WRITE = 2,
    /**
     * 执行
     */
    EXECUTE = 4,
    /**
     * 添加
     */
    APPEND = 8,
}

 
export namespace test { 
export enum Color {
    /**
     * 红色
     */
    RED = 1,
    /**
     * 绿色
     */
    GREEN = 2,
    /**
     * 蓝色
     */
    BLUE = 3,
    /**
     * 白色
     */
    WHITE = 4,
}

} 




export namespace demo {
export class constant {

    constructor(_json_: any) {
        if (_json_.x1 === undefined) { throw new Error() }
        this.x1 = _json_.x1
        if (_json_.x2 === undefined) { throw new Error() }
        this.x2 = _json_.x2
        if (_json_.x3 === undefined) { throw new Error() }
        this.x3 = _json_.x3
        if (_json_.x4 === undefined) { throw new Error() }
        this.x4 = _json_.x4
        if (_json_.x5 === undefined) { throw new Error() }
        this.x5 = _json_.x5
        if (_json_.x6 === undefined) { throw new Error() }
        this.x6 = _json_.x6
        if (_json_.x7 === undefined) { throw new Error() }
        { this.x7 = []; for(let _ele0 of _json_.x7) { let _e0; _e0 = _ele0; this.x7.push(_e0);}}
        if (_json_.x8 === undefined) { throw new Error() }
        this.x8 = _json_.x8
        if (_json_.x9 === undefined) { throw new Error() }
        this.x9 = _json_.x9
    }

    /**
     * 参数1
     */
    readonly x1: number
    /**
     * 道具
     */
    readonly x2: number
    readonly x3: number
    readonly x4: number
    readonly x5: number
    readonly x6: number
    readonly x7: number[]
    readonly x8: string
    readonly x9: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
    }
}

}


export namespace demo {
export class ConstantOne {

    constructor(_json_: any) {
        if (_json_.x1 === undefined) { throw new Error() }
        this.x1 = _json_.x1
        if (_json_.x2 === undefined) { throw new Error() }
        this.x2 = _json_.x2
        if (_json_.x3 === undefined) { throw new Error() }
        this.x3 = _json_.x3
        if (_json_.x4 === undefined) { throw new Error() }
        this.x4 = _json_.x4
        if (_json_.x5 === undefined) { throw new Error() }
        this.x5 = _json_.x5
        if (_json_.x6 === undefined) { throw new Error() }
        this.x6 = _json_.x6
        if (_json_.x7 === undefined) { throw new Error() }
        { this.x7 = []; for(let _ele0 of _json_.x7) { let _e0; _e0 = _ele0; this.x7.push(_e0);}}
        if (_json_.x8 === undefined) { throw new Error() }
        this.x8 = _json_.x8
        if (_json_.x9 === undefined) { throw new Error() }
        this.x9 = _json_.x9
    }

    /**
     * 参数1
     */
    readonly x1: number
    /**
     * 道具
     */
    readonly x2: number
    readonly x3: number
    readonly x4: number
    readonly x5: number
    readonly x6: number
    readonly x7: number[]
    readonly x8: string
    readonly x9: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
    }
}

}


export namespace demo {
export class item {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
        if (_json_.x1 === undefined) { throw new Error() }
        { this.x1 = []; for(let _ele0 of _json_.x1) { let _e0; _e0 = _ele0; this.x1.push(_e0);}}
        if (_json_.x2 === undefined) { throw new Error() }
        { this.x2 = []; for(let _ele0 of _json_.x2) { let _e0; _e0 = _ele0; this.x2.push(_e0);}}
        if (_json_.x3 === undefined) { throw new Error() }
        { this.x3 = []; for(let _ele0 of _json_.x3) { let _e0; _e0 = new test.Item(_ele0); this.x3.push(_e0);}}
        if (_json_.s1 === undefined) { throw new Error() }
        this.s1 = Shape.constructorFrom(_json_.s1)
        if (_json_.x4 === undefined) { throw new Error() }
        this.x4 = new vector2(_json_.x4)
        if (_json_.desc2 === undefined) { throw new Error() }
        this.desc2 = _json_.desc2
        if (_json_.x5 === undefined) { throw new Error() }
        this.x5 = _json_.x5
        if (_json_.x6 === undefined) { throw new Error() }
        this.x6 = _json_.x6
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 个数
     */
    readonly count: number
    readonly x1: number[]
    readonly x2: number[]
    readonly x3: test.Item[]
    readonly s1: Shape
    readonly x4: vector2
    readonly desc2: string
    readonly x5: number
    readonly x6: boolean

    resolve(tables:Tables) {
        
        
        
        
        
        
        for (let _e of this.x3) { _e?.resolve(tables); }
        this.s1?.resolve(tables);
        
        
        
        
    }
}

}


export namespace demo {
export class lang {

    constructor(_json_: any) {
        if (_json_.key === undefined) { throw new Error() }
        this.key = _json_.key
        if (_json_.zh === undefined) { throw new Error() }
        this.zh = _json_.zh
        if (_json_.en === undefined) { throw new Error() }
        this.en = _json_.en
    }

    readonly key: string
    readonly zh: string
    readonly en: string

    resolve(tables:Tables) {
        
        
        
    }
}

}


export namespace demo {
export class Manykey {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
        if (_json_.x1 === undefined) { throw new Error() }
        { this.x1 = []; for(let _ele0 of _json_.x1) { let _e0; _e0 = _ele0; this.x1.push(_e0);}}
        if (_json_.x2 === undefined) { throw new Error() }
        { this.x2 = []; for(let _ele0 of _json_.x2) { let _e0; _e0 = _ele0; this.x2.push(_e0);}}
        if (_json_.x3 === undefined) { throw new Error() }
        { this.x3 = []; for(let _ele0 of _json_.x3) { let _e0; _e0 = new test.Item(_ele0); this.x3.push(_e0);}}
        if (_json_.s1 === undefined) { throw new Error() }
        this.s1 = Shape.constructorFrom(_json_.s1)
        if (_json_.x4 === undefined) { throw new Error() }
        this.x4 = new vector2(_json_.x4)
        if (_json_.desc2 === undefined) { throw new Error() }
        this.desc2 = _json_.desc2
        if (_json_.x5 === undefined) { throw new Error() }
        this.x5 = _json_.x5
        if (_json_.x6 === undefined) { throw new Error() }
        this.x6 = _json_.x6
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 个数
     */
    readonly count: number
    readonly x1: number[]
    readonly x2: number[]
    readonly x3: test.Item[]
    readonly s1: Shape
    readonly x4: vector2
    readonly desc2: string
    readonly x5: number
    readonly x6: boolean

    resolve(tables:Tables) {
        
        
        
        
        
        
        for (let _e of this.x3) { _e?.resolve(tables); }
        this.s1?.resolve(tables);
        
        
        
        
    }
}

}


export namespace demo {
export class manyRow10000 {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.id2 === undefined) { throw new Error() }
        this.id2 = _json_.id2
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
    }

    readonly id: number
    /**
     * id
     */
    readonly id2: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 个数
     */
    readonly count: number

    resolve(tables:Tables) {
        
        
        
        
        
    }
}

}


export namespace demo {
export class One {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
        if (_json_.x1 === undefined) { throw new Error() }
        { this.x1 = []; for(let _ele0 of _json_.x1) { let _e0; _e0 = _ele0; this.x1.push(_e0);}}
        if (_json_.x2 === undefined) { throw new Error() }
        { this.x2 = []; for(let _ele0 of _json_.x2) { let _e0; _e0 = _ele0; this.x2.push(_e0);}}
        if (_json_.x3 === undefined) { throw new Error() }
        { this.x3 = []; for(let _ele0 of _json_.x3) { let _e0; _e0 = new test.Item(_ele0); this.x3.push(_e0);}}
        if (_json_.s1 === undefined) { throw new Error() }
        this.s1 = Shape.constructorFrom(_json_.s1)
        if (_json_.x4 === undefined) { throw new Error() }
        this.x4 = new vector2(_json_.x4)
        if (_json_.desc2 === undefined) { throw new Error() }
        this.desc2 = _json_.desc2
        if (_json_.x5 === undefined) { throw new Error() }
        this.x5 = _json_.x5
        if (_json_.x6 === undefined) { throw new Error() }
        this.x6 = _json_.x6
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 个数
     */
    readonly count: number
    readonly x1: number[]
    readonly x2: number[]
    readonly x3: test.Item[]
    readonly s1: Shape
    readonly x4: vector2
    readonly desc2: string
    readonly x5: number
    readonly x6: boolean

    resolve(tables:Tables) {
        
        
        
        
        
        
        for (let _e of this.x3) { _e?.resolve(tables); }
        this.s1?.resolve(tables);
        
        
        
        
    }
}

}


export namespace demo {
export class reward {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
        if (_json_.item_id === undefined) { throw new Error() }
        this.itemId = _json_.item_id
        if (_json_.quality === undefined) { throw new Error() }
        this.quality = _json_.quality
        if (_json_.x2 === undefined) { throw new Error() }
        this.x2 = _json_.x2
        if (_json_.x3 === undefined) { throw new Error() }
        this.x3 = _json_.x3
        if (_json_.item1 === undefined) { throw new Error() }
        this.item1 = new test.Item(_json_.item1)
        if (_json_.item2 === undefined) { throw new Error() }
        this.item2 = new test.Item(_json_.item2)
        if (_json_.x4 === undefined) { throw new Error() }
        { this.x4 = []; for(let _ele0 of _json_.x4) { let _e0; _e0 = _ele0; this.x4.push(_e0);}}
        if (_json_.x5 === undefined) { throw new Error() }
        { this.x5 = []; for(let _ele0 of _json_.x5) { let _e0; _e0 = _ele0; this.x5.push(_e0);}}
        if (_json_.items === undefined) { throw new Error() }
        { this.items = []; for(let _ele0 of _json_.items) { let _e0; _e0 = new test.Item(_ele0); this.items.push(_e0);}}
        if (_json_.m1 === undefined) { throw new Error() }
        this.m1 = new Map<number, string>(); for(var _entry0_ of _json_.m1) { let _k0; _k0 = _entry0_[0];  let _v0;  _v0 = _entry0_[1]; this.m1.set(_k0, _v0);  }
        if (_json_.m2 === undefined) { throw new Error() }
        this.m2 = new Map<number, number>(); for(var _entry0_ of _json_.m2) { let _k0; _k0 = _entry0_[0];  let _v0;  _v0 = _entry0_[1]; this.m2.set(_k0, _v0);  }
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 个数
     */
    readonly count: number
    readonly itemId: number
    itemId_ref: demo.item | undefined
    /**
     * 颜色
     */
    readonly quality: test.Color
    /**
     * 访问测试1
     */
    readonly x2: AccessFLag
    /**
     * 访问测试2
     */
    readonly x3: AccessFLag
    readonly item1: test.Item
    readonly item2: test.Item
    readonly x4: string[]
    readonly x5: number[]
    /**
     * 多行配置数组
     */
    readonly items: test.Item[]
    readonly m1: Map<number, string>
    readonly m2: Map<number, number>

    resolve(tables:Tables) {
        
        
        
        
        this.itemId_ref = tables.Tbitem.get(this.itemId)
        
        
        
        this.item1?.resolve(tables);
        this.item2?.resolve(tables);
        
        
        for (let _e of this.items) { _e?.resolve(tables); }
        
        
    }
}

}



export abstract class Shape {
    static constructorFrom(_json_: any): Shape{
        switch (_json_["$type"]) {
            case 'Circle': return new Circle(_json_)
            case 'Rect': return new Rect(_json_)
            default: throw new Error()
        }
    }

    constructor(_json_: any) {
        if (_json_.i === undefined) { throw new Error() }
        this.i = _json_.i
    }

    readonly i: number

    resolve(tables:Tables) {
        
    }
}





export class Circle extends Shape {

    constructor(_json_: any) {
        super(_json_)
        if (_json_.radius === undefined) { throw new Error() }
        this.radius = _json_.radius
    }

    readonly radius: number

    resolve(tables:Tables) {
        super.resolve(tables)
        
    }
}





export class Rect extends Shape {

    constructor(_json_: any) {
        super(_json_)
        if (_json_.width === undefined) { throw new Error() }
        this.width = _json_.width
        if (_json_.height === undefined) { throw new Error() }
        this.height = _json_.height
    }

    readonly width: number
    readonly height: number

    resolve(tables:Tables) {
        super.resolve(tables)
        
        
    }
}




export namespace test {
export class Item {

    constructor(_json_: any) {
        if (_json_.item_id === undefined) { throw new Error() }
        this.itemId = _json_.item_id
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
    }

    /**
     * 道具id
     */
    readonly itemId: number
    /**
     * 道具个数
     */
    readonly count: number

    resolve(tables:Tables) {
        
        
    }
}

}



export class vector2 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
    }

    readonly x: number
    readonly y: number

    resolve(tables:Tables) {
        
        
    }
}





export class vector3 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
        if (_json_.z === undefined) { throw new Error() }
        this.z = _json_.z
    }

    readonly x: number
    readonly y: number
    readonly z: number

    resolve(tables:Tables) {
        
        
        
    }
}





export class vector4 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
        if (_json_.z === undefined) { throw new Error() }
        this.z = _json_.z
        if (_json_.w === undefined) { throw new Error() }
        this.w = _json_.w
    }

    readonly x: number
    readonly y: number
    readonly z: number
    readonly w: number

    resolve(tables:Tables) {
        
        
        
        
    }
}





export namespace demo {
/**
 * 联合索引
 */
export class TbManyKey {
    private _dataList: demo.Manykey[]
    
    constructor(_json_: any) {
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.Manykey
            _v = new demo.Manykey(_json2_)
            this._dataList.push(_v)
        }
    }

    getDataList(): demo.Manykey[] { return this._dataList }

    get(index: number): demo.Manykey | undefined { return this._dataList[index] }
    
    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace demo {
/**
 * 行的结构单例（全局常量数据用）
 */
export class TbOne {

    private _data: demo.One
    constructor(_json_: any) {
        if (_json_.length != 1) throw new Error('table mode=one, but size != 1')
        this._data = new demo.One(_json_[0])
    }

    getData(): demo.One { return this._data; }

    /**
     * id
     */
    get  id(): number { return this._data.id; }
    /**
     * 名称
     */
    get  name(): string { return this._data.name; }
    /**
     * 描述
     */
    get  desc(): string { return this._data.desc; }
    /**
     * 个数
     */
    get  count(): number { return this._data.count; }
    get  x1(): number[] { return this._data.x1; }
    get  x2(): number[] { return this._data.x2; }
    get  x3(): test.Item[] { return this._data.x3; }
    get  s1(): Shape { return this._data.s1; }
    get  x4(): vector2 { return this._data.x4; }
    get  desc2(): string { return this._data.desc2; }
    get  x5(): number { return this._data.x5; }
    get  x6(): boolean { return this._data.x6; }

    resolve(tables:Tables)
    {
        this._data.resolve(tables)
    }
    
}
}


export namespace demo {
/**
 * 竖的单例结构（全局常量数据用）
 */
export class TbConstantOne {

    private _data: demo.ConstantOne
    constructor(_json_: any) {
        if (_json_.length != 1) throw new Error('table mode=one, but size != 1')
        this._data = new demo.ConstantOne(_json_[0])
    }

    getData(): demo.ConstantOne { return this._data; }

    /**
     * 参数1
     */
    get  x1(): number { return this._data.x1; }
    /**
     * 道具
     */
    get  x2(): number { return this._data.x2; }
    get  x3(): number { return this._data.x3; }
    get  x4(): number { return this._data.x4; }
    get  x5(): number { return this._data.x5; }
    get  x6(): number { return this._data.x6; }
    get  x7(): number[] { return this._data.x7; }
    get  x8(): string { return this._data.x8; }
    get  x9(): number { return this._data.x9; }

    resolve(tables:Tables)
    {
        this._data.resolve(tables)
    }
    
}
}


export namespace demo {
export class Tbconstant {
    private _dataMap: Map<number, demo.constant>
    private _dataList: demo.constant[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, demo.constant>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.constant
            _v = new demo.constant(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.x1, _v)
        }
    }

    getDataMap(): Map<number, demo.constant> { return this._dataMap; }
    getDataList(): demo.constant[] { return this._dataList; }

    get(key: number): demo.constant | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace demo {
export class Tbitem {
    private _dataMap: Map<number, demo.item>
    private _dataList: demo.item[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, demo.item>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.item
            _v = new demo.item(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, demo.item> { return this._dataMap; }
    getDataList(): demo.item[] { return this._dataList; }

    get(key: number): demo.item | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace demo {
export class Tblang {
    private _dataMap: Map<string, demo.lang>
    private _dataList: demo.lang[]
    constructor(_json_: any) {
        this._dataMap = new Map<string, demo.lang>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.lang
            _v = new demo.lang(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.key, _v)
        }
    }

    getDataMap(): Map<string, demo.lang> { return this._dataMap; }
    getDataList(): demo.lang[] { return this._dataList; }

    get(key: string): demo.lang | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace demo {
export class TbmanyRow10000 {
    private _dataMap: Map<number, demo.manyRow10000>
    private _dataList: demo.manyRow10000[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, demo.manyRow10000>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.manyRow10000
            _v = new demo.manyRow10000(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, demo.manyRow10000> { return this._dataMap; }
    getDataList(): demo.manyRow10000[] { return this._dataList; }

    get(key: number): demo.manyRow10000 | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace demo {
export class Tbreward {
    private _dataMap: Map<number, demo.reward>
    private _dataList: demo.reward[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, demo.reward>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.reward
            _v = new demo.reward(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, demo.reward> { return this._dataMap; }
    getDataList(): demo.reward[] { return this._dataList; }

    get(key: number): demo.reward | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}



type JsonLoader = (file: string) => any

export class Tables {
    private _TbManyKey: demo.TbManyKey
    /**
     * 联合索引
     */
    get TbManyKey(): demo.TbManyKey  { return this._TbManyKey;}
    private _TbOne: demo.TbOne
    /**
     * 行的结构单例（全局常量数据用）
     */
    get TbOne(): demo.TbOne  { return this._TbOne;}
    private _TbConstantOne: demo.TbConstantOne
    /**
     * 竖的单例结构（全局常量数据用）
     */
    get TbConstantOne(): demo.TbConstantOne  { return this._TbConstantOne;}
    private _Tbconstant: demo.Tbconstant
    get Tbconstant(): demo.Tbconstant  { return this._Tbconstant;}
    private _Tbitem: demo.Tbitem
    get Tbitem(): demo.Tbitem  { return this._Tbitem;}
    private _Tblang: demo.Tblang
    get Tblang(): demo.Tblang  { return this._Tblang;}
    private _TbmanyRow10000: demo.TbmanyRow10000
    get TbmanyRow10000(): demo.TbmanyRow10000  { return this._TbmanyRow10000;}
    private _Tbreward: demo.Tbreward
    get Tbreward(): demo.Tbreward  { return this._Tbreward;}

    constructor(loader: JsonLoader) {
        this._TbManyKey = new demo.TbManyKey(loader('demo_tbmanykey'))
        this._TbOne = new demo.TbOne(loader('demo_tbone'))
        this._TbConstantOne = new demo.TbConstantOne(loader('demo_tbconstantone'))
        this._Tbconstant = new demo.Tbconstant(loader('demo_tbconstant'))
        this._Tbitem = new demo.Tbitem(loader('demo_tbitem'))
        this._Tblang = new demo.Tblang(loader('demo_tblang'))
        this._TbmanyRow10000 = new demo.TbmanyRow10000(loader('demo_tbmanyrow10000'))
        this._Tbreward = new demo.Tbreward(loader('demo_tbreward'))

        this._TbManyKey.resolve(this)
        this._TbOne.resolve(this)
        this._TbConstantOne.resolve(this)
        this._Tbconstant.resolve(this)
        this._Tbitem.resolve(this)
        this._Tblang.resolve(this)
        this._TbmanyRow10000.resolve(this)
        this._Tbreward.resolve(this)
    }
}

