
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
public sealed partial class lang : Luban.BeanBase
{
    public lang(JsonElement _buf) 
    {
        Key = _buf.GetProperty("key").GetString();
        Zh = _buf.GetProperty("zh").GetString();
        En = _buf.GetProperty("en").GetString();
    }

    public static lang Deserializelang(JsonElement _buf)
    {
        return new demo.lang(_buf);
    }

    public readonly string Key;
    public readonly string Zh;
    public readonly string En;
   
    public const int __ID__ = 750650137;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "zh:" + Zh + ","
        + "en:" + En + ","
        + "}";
    }
}
}

