
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
public sealed partial class manyRow10000 : Luban.BeanBase
{
    public manyRow10000(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Id2 = _buf.GetProperty("id2").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        Count = _buf.GetProperty("count").GetInt32();
    }

    public static manyRow10000 DeserializemanyRow10000(JsonElement _buf)
    {
        return new demo.manyRow10000(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// id
    /// </summary>
    public readonly int Id2;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = 1325996993;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "id2:" + Id2 + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

