
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
public sealed partial class One : Luban.BeanBase
{
    public One(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        Count = _buf.GetProperty("count").GetInt32();
        { var __json0 = _buf.GetProperty("x1"); X1 = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  X1.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("x2"); X2 = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  X2.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("x3"); int _n0 = __json0.GetArrayLength(); X3 = new test.Item[_n0]; int __index0=0; foreach(JsonElement __e0 in __json0.EnumerateArray()) { test.Item __v0;  __v0 = global::cfg.test.Item.DeserializeItem(__e0);  X3[__index0++] = __v0; }   }
        S1 = global::cfg.Shape.DeserializeShape(_buf.GetProperty("s1"));
        X4 = global::cfg.vector2.Deserializevector2(_buf.GetProperty("x4"));
        Desc2 = _buf.GetProperty("desc2").GetString();
        X5 = _buf.GetProperty("x5").GetInt64();
        X6 = _buf.GetProperty("x6").GetBoolean();
    }

    public static One DeserializeOne(JsonElement _buf)
    {
        return new demo.One(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly int Count;
    public readonly System.Collections.Generic.List<int> X1;
    public readonly System.Collections.Generic.List<int> X2;
    public readonly test.Item[] X3;
    public readonly Shape S1;
    public readonly vector2 X4;
    public readonly string Desc2;
    public readonly long X5;
    public readonly bool X6;
   
    public const int __ID__ = 855471035;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in X3) { _e?.ResolveRef(tables); }
        S1?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "x1:" + Luban.StringUtil.CollectionToString(X1) + ","
        + "x2:" + Luban.StringUtil.CollectionToString(X2) + ","
        + "x3:" + Luban.StringUtil.CollectionToString(X3) + ","
        + "s1:" + S1 + ","
        + "x4:" + X4 + ","
        + "desc2:" + Desc2 + ","
        + "x5:" + X5 + ","
        + "x6:" + X6 + ","
        + "}";
    }
}
}

