
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
public sealed partial class reward : Luban.BeanBase
{
    public reward(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        Count = _buf.GetProperty("count").GetInt32();
        ItemId = _buf.GetProperty("item_id").GetInt32();
        ItemId_Ref = null;
        Hp = _buf.GetProperty("hp").GetInt32();
        Quality = (test.Color)_buf.GetProperty("quality").GetInt32();
        X2 = (AccessFLag)_buf.GetProperty("x2").GetInt32();
        X3 = (AccessFLag)_buf.GetProperty("x3").GetInt32();
        Item1 = global::cfg.test.Item.DeserializeItem(_buf.GetProperty("item1"));
        Item2 = global::cfg.test.Item.DeserializeItem(_buf.GetProperty("item2"));
        { var __json0 = _buf.GetProperty("x4"); int _n0 = __json0.GetArrayLength(); X4 = new string[_n0]; int __index0=0; foreach(JsonElement __e0 in __json0.EnumerateArray()) { string __v0;  __v0 = __e0.GetString();  X4[__index0++] = __v0; }   }
        { var __json0 = _buf.GetProperty("x5"); X5 = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  X5.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("items"); int _n0 = __json0.GetArrayLength(); Items = new test.Item[_n0]; int __index0=0; foreach(JsonElement __e0 in __json0.EnumerateArray()) { test.Item __v0;  __v0 = global::cfg.test.Item.DeserializeItem(__e0);  Items[__index0++] = __v0; }   }
        { var __json0 = _buf.GetProperty("m1"); M1 = new System.Collections.Generic.Dictionary<int, string>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int _k0;  _k0 = __e0[0].GetInt32(); string _v0;  _v0 = __e0[1].GetString();  M1.Add(_k0, _v0); }   }
        { var __json0 = _buf.GetProperty("m2"); M2 = new System.Collections.Generic.Dictionary<int, int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int _k0;  _k0 = __e0[0].GetInt32(); int _v0;  _v0 = __e0[1].GetInt32();  M2.Add(_k0, _v0); }   }
        { var __json0 = _buf.GetProperty("m3"); M3 = new System.Collections.Generic.HashSet<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  M3.Add(__v0); }   }
    }

    public static reward Deserializereward(JsonElement _buf)
    {
        return new demo.reward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly int Count;
    public readonly int ItemId;
    public demo.item ItemId_Ref;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 颜色
    /// </summary>
    public readonly test.Color Quality;
    /// <summary>
    /// 访问测试1
    /// </summary>
    public readonly AccessFLag X2;
    /// <summary>
    /// 访问测试2
    /// </summary>
    public readonly AccessFLag X3;
    public readonly test.Item Item1;
    public readonly test.Item Item2;
    public readonly string[] X4;
    public readonly System.Collections.Generic.List<int> X5;
    /// <summary>
    /// 多行配置数组
    /// </summary>
    public readonly test.Item[] Items;
    public readonly System.Collections.Generic.Dictionary<int, string> M1;
    public readonly System.Collections.Generic.Dictionary<int, int> M2;
    public readonly System.Collections.Generic.HashSet<int> M3;
   
    public const int __ID__ = -3989094;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ItemId_Ref = tables.Tbitem.GetOrDefault(ItemId);
        Item1?.ResolveRef(tables);
        Item2?.ResolveRef(tables);
        foreach (var _e in Items) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "itemId:" + ItemId + ","
        + "hp:" + Hp + ","
        + "quality:" + Quality + ","
        + "x2:" + X2 + ","
        + "x3:" + X3 + ","
        + "item1:" + Item1 + ","
        + "item2:" + Item2 + ","
        + "x4:" + Luban.StringUtil.CollectionToString(X4) + ","
        + "x5:" + Luban.StringUtil.CollectionToString(X5) + ","
        + "items:" + Luban.StringUtil.CollectionToString(Items) + ","
        + "m1:" + Luban.StringUtil.CollectionToString(M1) + ","
        + "m2:" + Luban.StringUtil.CollectionToString(M2) + ","
        + "m3:" + Luban.StringUtil.CollectionToString(M3) + ","
        + "}";
    }
}
}

