
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
public partial class Tbconstant
{
    private readonly System.Collections.Generic.Dictionary<int, demo.constant> _dataMap;
    private readonly System.Collections.Generic.List<demo.constant> _dataList;
    
    public Tbconstant(JsonElement _buf)
    {
        int count = _buf.GetArrayLength();
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.constant>(count);
        _dataList = new System.Collections.Generic.List<demo.constant>(count);
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            demo.constant _v;
            _v = global::cfg.demo.constant.Deserializeconstant(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.X1, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.constant> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.constant> DataList => _dataList;

    public demo.constant GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.constant Get(int key) => _dataMap[key];
    public demo.constant this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

