
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
public partial class Tblang
{
    private readonly System.Collections.Generic.Dictionary<string, demo.lang> _dataMap;
    private readonly System.Collections.Generic.List<demo.lang> _dataList;
    
    public Tblang(JsonElement _buf)
    {
        int count = _buf.GetArrayLength();
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.lang>(count);
        _dataList = new System.Collections.Generic.List<demo.lang>(count);
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            demo.lang _v;
            _v = global::cfg.demo.lang.Deserializelang(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.lang> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.lang> DataList => _dataList;

    public demo.lang GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.lang Get(string key) => _dataMap[key];
    public demo.lang this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

