
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
/// <summary>
/// 联合索引
/// </summary>
public partial class TbManyKey
{
    private readonly System.Collections.Generic.List<demo.Manykey> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), demo.Manykey> _dataMapUnion;

    public TbManyKey(JsonElement _buf)
    {
        int count = _buf.GetArrayLength();
        _dataList = new System.Collections.Generic.List<demo.Manykey>(count);
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            demo.Manykey _v;
            _v = global::cfg.demo.Manykey.DeserializeManykey(_ele);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), demo.Manykey>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.Id, _v.Count), _v);
            }
    }

    public System.Collections.Generic.List<demo.Manykey> DataList => _dataList;

    public demo.Manykey Get(int id, int count) => _dataMapUnion.TryGetValue((id, count), out demo.Manykey __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

