
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
public partial class TbmanyRow10000
{
    private readonly System.Collections.Generic.Dictionary<int, demo.manyRow10000> _dataMap;
    private readonly System.Collections.Generic.List<demo.manyRow10000> _dataList;
    
    public TbmanyRow10000(JsonElement _buf)
    {
        int count = _buf.GetArrayLength();
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.manyRow10000>(count);
        _dataList = new System.Collections.Generic.List<demo.manyRow10000>(count);
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            demo.manyRow10000 _v;
            _v = global::cfg.demo.manyRow10000.DeserializemanyRow10000(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.manyRow10000> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.manyRow10000> DataList => _dataList;

    public demo.manyRow10000 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.manyRow10000 Get(int key) => _dataMap[key];
    public demo.manyRow10000 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

