
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.demo
{
/// <summary>
/// 行的结构单例（全局常量数据用）
/// </summary>
public partial class TbOne
{

     private readonly demo.One _data;

     public demo.One Data => _data;

    public TbOne(JsonElement _buf)
    {
        int n = _buf.GetArrayLength();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::cfg.demo.One.DeserializeOne(_buf[0]);
    }


    /// <summary>
    /// id
    /// </summary>
     public int Id => _data.Id;
    /// <summary>
    /// 名称
    /// </summary>
     public string Name => _data.Name;
    /// <summary>
    /// 描述
    /// </summary>
     public string Desc => _data.Desc;
    /// <summary>
    /// 个数
    /// </summary>
     public int Count => _data.Count;
     public System.Collections.Generic.List<int> X1 => _data.X1;
     public System.Collections.Generic.List<int> X2 => _data.X2;
     public test.Item[] X3 => _data.X3;
     public Shape S1 => _data.S1;
     public vector2 X4 => _data.X4;
     public string Desc2 => _data.Desc2;
     public long X5 => _data.X5;
     public bool X6 => _data.X6;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

