
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.test
{ 
    public enum Color
    {
        /// <summary>
        /// 红色
        /// </summary>
        RED = 1,
        /// <summary>
        /// 绿色
        /// </summary>
        GREEN = 2,
        /// <summary>
        /// 蓝色
        /// </summary>
        BLUE = 3,
        /// <summary>
        /// 白色
        /// </summary>
        WHITE = 4,
    }

} 

