
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.test
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JsonElement _buf) 
    {
        ItemId = _buf.GetProperty("item_id").GetInt32();
        Count = _buf.GetProperty("count").GetInt32();
    }

    public static Item DeserializeItem(JsonElement _buf)
    {
        return new test.Item(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 道具个数
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = -1226641649;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

