
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


 
export enum AccessFLag {
    /**
     * 读
     */
    READ = 1,
    /**
     * 写
     */
    WRITE = 2,
    /**
     * 执行
     */
    EXECUTE = 3,
    /**
     * 读写
     */
    READ_WRITE = 4,
}

 
export namespace test { 
export enum Color {
    /**
     * 红色
     */
    RED = 1,
    /**
     * 绿色
     */
    GREEN = 2,
    /**
     * 蓝色
     */
    BLUE = 3,
    /**
     * 白色
     */
    WHITE = 4,
}

} 




export namespace demo {
export class item {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 个数
     */
    readonly count: number

    resolve(tables:Tables) {
        
        
        
        
    }
}

}


export namespace demo {
export class reward {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.count === undefined) { throw new Error() }
        this.count = _json_.count
        if (_json_.color === undefined) { throw new Error() }
        this.color = _json_.color
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 个数
     */
    readonly count: number
    /**
     * 颜色
     */
    readonly color: test.Color

    resolve(tables:Tables) {
        
        
        
        
        
    }
}

}



export class vector2 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
    }

    readonly x: number
    readonly y: number

    resolve(tables:Tables) {
        
        
    }
}





export class vector3 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
        if (_json_.z === undefined) { throw new Error() }
        this.z = _json_.z
    }

    readonly x: number
    readonly y: number
    readonly z: number

    resolve(tables:Tables) {
        
        
        
    }
}





export class vector4 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
        if (_json_.z === undefined) { throw new Error() }
        this.z = _json_.z
        if (_json_.w === undefined) { throw new Error() }
        this.w = _json_.w
    }

    readonly x: number
    readonly y: number
    readonly z: number
    readonly w: number

    resolve(tables:Tables) {
        
        
        
        
    }
}





export namespace demo {
export class Tbitem {
    private _dataMap: Map<number, demo.item>
    private _dataList: demo.item[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, demo.item>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.item
            _v = new demo.item(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, demo.item> { return this._dataMap; }
    getDataList(): demo.item[] { return this._dataList; }

    get(key: number): demo.item | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace demo {
export class Tbreward {
    private _dataMap: Map<number, demo.reward>
    private _dataList: demo.reward[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, demo.reward>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: demo.reward
            _v = new demo.reward(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, demo.reward> { return this._dataMap; }
    getDataList(): demo.reward[] { return this._dataList; }

    get(key: number): demo.reward | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}



type JsonLoader = (file: string) => any

export class Tables {
    private _Tbitem: demo.Tbitem
    get Tbitem(): demo.Tbitem  { return this._Tbitem;}
    private _Tbreward: demo.Tbreward
    get Tbreward(): demo.Tbreward  { return this._Tbreward;}

    constructor(loader: JsonLoader) {
        this._Tbitem = new demo.Tbitem(loader('demo_tbitem'))
        this._Tbreward = new demo.Tbreward(loader('demo_tbreward'))

        this._Tbitem.resolve(this)
        this._Tbreward.resolve(this)
    }
}

