
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    [System.Flags]
    public enum AccessFLag
    {
        /// <summary>
        /// 读
        /// </summary>
        READ = 1,
        /// <summary>
        /// 写
        /// </summary>
        WRITE = 2,
        /// <summary>
        /// 执行
        /// </summary>
        EXECUTE = 4,
        /// <summary>
        /// 添加
        /// </summary>
        APPEND = 8,
    }

} 

