
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Circle : Shape
{
    public Circle(JsonElement _buf)  : base(_buf) 
    {
        Radius = _buf.GetProperty("radius").GetSingle();
    }

    public static Circle DeserializeCircle(JsonElement _buf)
    {
        return new Circle(_buf);
    }

    public readonly float Radius;
   
    public const int __ID__ = 2018617584;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "i:" + I + ","
        + "radius:" + Radius + ","
        + "}";
    }
}
}

