
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Rect : Shape
{
    public Rect(JsonElement _buf)  : base(_buf) 
    {
        Width = _buf.GetProperty("width").GetSingle();
        Height = _buf.GetProperty("height").GetSingle();
    }

    public static Rect DeserializeRect(JsonElement _buf)
    {
        return new Rect(_buf);
    }

    public readonly float Width;
    public readonly float Height;
   
    public const int __ID__ = 2543108;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "i:" + I + ","
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "}";
    }
}
}

