
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public abstract partial class Shape : Luban.BeanBase
{
    public Shape(JsonElement _buf) 
    {
        I = _buf.GetProperty("i").GetInt32();
    }

    public static Shape DeserializeShape(JsonElement _buf)
    {
        switch (_buf.GetProperty("$type").GetString())
        {
            case "Circle": return new Circle(_buf);
            case "Rect": return new Rect(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int I;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "i:" + I + ","
        + "}";
    }
}
}

