
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 联合索引
    /// </summary>
    public demo.TbManyKey TbManyKey {get; }
    /// <summary>
    /// 行的结构单例（全局常量数据用）
    /// </summary>
    public demo.TbOne TbOne {get; }
    /// <summary>
    /// 竖的单例结构（全局常量数据用）
    /// </summary>
    public demo.TbConstantOne TbConstantOne {get; }
    public TbTest TbTest {get; }
    public demo.Tbconstant Tbconstant {get; }
    public demo.Tbitem Tbitem {get; }
    public demo.Tblang Tblang {get; }
    public demo.TbmanyRow10000 TbmanyRow10000 {get; }
    public demo.Tbreward Tbreward {get; }

    public Tables(System.Func<string, JsonElement> loader)
    {
        TbManyKey = new demo.TbManyKey(loader("demo_tbmanykey"));
        TbOne = new demo.TbOne(loader("demo_tbone"));
        TbConstantOne = new demo.TbConstantOne(loader("demo_tbconstantone"));
        TbTest = new TbTest(loader("tbtest"));
        Tbconstant = new demo.Tbconstant(loader("demo_tbconstant"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        Tblang = new demo.Tblang(loader("demo_tblang"));
        TbmanyRow10000 = new demo.TbmanyRow10000(loader("demo_tbmanyrow10000"));
        Tbreward = new demo.Tbreward(loader("demo_tbreward"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbManyKey.ResolveRef(this);
        TbOne.ResolveRef(this);
        TbConstantOne.ResolveRef(this);
        TbTest.ResolveRef(this);
        Tbconstant.ResolveRef(this);
        Tbitem.ResolveRef(this);
        Tblang.ResolveRef(this);
        TbmanyRow10000.ResolveRef(this);
        Tbreward.ResolveRef(this);
    }
}

}
